---
version: 2
sphinx:
  builder: html
  fail_on_warning: false
  configuration: documentation/source/conf.py
formats: []
python:
  version: "3.7"
  install:
    - method: pip
      path: .
      extra_requirements:
        - pib-docs
  system_packages: false
