#!/bin/bash
# shellcheck disable=SC2034

autocomplete() {

  if command -v pib_cli >/dev/null 2>&1; then
    eval "$(_PIB_CLI_COMPLETE=source_bash pib_cli)"
    eval "$(_DEV_COMPLETE=source_bash dev)"
  fi

}

shellcheck_scripts() {
  find scripts -type f -exec shellcheck -x "{}" \;
}

dev_identifier() {
  Cyan='\033[36m'         # Cyan
  BRed='\033[31m'         # Red
  BGreen='\033[32m'       # Green
  NC="\\033[0m"            # Color Reset
  echo -en "(${BGreen}pib_cli${NC})"
}

autocomplete
PROMPT_COMMAND="dev_identifier; $PROMPT_COMMAND"
